import { query } from "./_generated/server";
import { User } from '../src/types/users';

export const get = query({
  handler: async () => {
    const dummyUsers: User[] = [
    {
      id: '#876364',
      avatar: '/avatars/avatar-1.jpg',
      name: 'Arrora gaur',
      email: 'arroragaur@gmail.com',
      date: '12 Dec, 2020',
      status: 'Complete',
      starred: true,
      checked: false,
      },
      {
      id: '#876123',
      avatar: '/avatars/avatar-2.jpg',
      name: 'James Mullican',
      email: 'jamesmullican@gmail.com',
      date: '10 Dec, 2020',
      status: 'Pending',
      starred: false,
      checked: false,
      },
      {
      id: '#876213',
      avatar: '/avatars/avatar-3.jpg',
      name: 'Robert Bacins',
      email: 'robertbacins@gmail.com',
      date: '09 Dec, 2020',
      status: 'Complete',
      starred: false,
      checked: true,
      },
      {
      id: '#876987',
      avatar: '/avatars/avatar-4.jpg',
      name: 'Bethany Jackson',
      email: 'bethanyjackson@gmail.com',
      date: '09 Dec, 2020',
      status: 'Cancel',
      starred: false,
      checked: true,
      },
      {
      id: '#871345',
      avatar: '/avatars/avatar-5.jpg',
      name: 'Anne Jacob',
      email: 'annejacob@gmail.com',
      date: '10 Dec, 2020',
      status: 'Complete',
      starred: false,
      checked: false,
      },
      {
      id: '#872345',
      avatar: '/avatars/avatar-6.jpg',
      name: 'Bethany Jackson',
      email: 'bethanyjackson@gmail.com',
      date: '10 Dec, 2020',
      status: 'Pending',
      starred: false,
      checked: true,
      },
      {
      id: '#872346',
      avatar: '/avatars/avatar-7.jpg',
      name: 'James Mullican',
      email: 'jamesmullican@gmail.com',
      date: '10 Dec, 2020',
      status: 'Complete',
      starred: false,
      checked: false,
      },
      {
      id: '#873245',
      avatar: '/avatars/avatar-8.jpg',
      name: 'Jhon Deo',
      email: 'jhondeo32@gmail.com',
      date: '08 Dec, 2020',
      status: 'Complete',
      starred: true,
      checked: false,
      },
      {
      id: '#876364',
      avatar: '/avatars/avatar-9.jpg',
      name: 'Bethany Jackson',
      email: 'bethanyjackson@gmail.com',
      date: '02 Dec, 2020',
      status: 'Cancel',
      starred: true,
      checked: false,
      },
      {
      id: '#878769',
      avatar: '/avatars/avatar-10.jpg',
      name: 'James Mullican',
      email: 'jamesmullican@gmail.com',
      date: '01 Dec, 2020',
      status: 'Pending',
      starred: false,
      checked: true,
      },
    ];
    return dummyUsers;
  },
});